repos:
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        name: mypy_deeplut
        files: deeplut*
      - id: mypy
        name: mypy_tests
        files: tests*
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8_deeplut
        files: deeplut*
        additional_dependencies:
          - flake8-print==3.1.4
      - id: flake8
        name: flake8_tests
        files: tests*
        additional_dependencies:
          - flake8-print==3.1.4